# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['srt_maker/main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'torch',
        'torch._C',
        'whisper',
        'silero_vad',
        'pyqtgraph',
        'pyqtgraph.graphicsItems',
        'opencv_python',
        'cv2',
        'numpy',
        'ffmpeg',
        'ffmpeg._ffmpeg',
        'srt_maker',
        'srt_maker.core',
        'srt_maker.core.config',
        'srt_maker.core.subtitle_model',
        'srt_maker.core.subtitle_list',
        'srt_maker.core.timecode',
        'srt_maker.audio',
        'srt_maker.audio.extractor',
        'srt_maker.audio.vad',
        'srt_maker.speech',
        'srt_maker.speech.base',
        'srt_maker.speech.whisper_recognizer',
        'srt_maker.speech.qwen_asr_recognizer',
        'srt_maker.speech.cloud_recognizer',
        'srt_maker.video',
        'srt_maker.video.ffmpeg_wrapper',
        'srt_maker.video.player',
        'srt_maker.video.burner',
        'srt_maker.io',
        'srt_maker.io.srt_parser',
        'srt_maker.io.ass_parser',
        'srt_maker.ui',
        'srt_maker.ui.main_window',
        'srt_maker.ui.video_preview',
        'srt_maker.ui.waveform_view',
        'srt_maker.ui.subtitle_editor',
        'srt_maker.ui.style_panel',
        'srt_maker.ui.recognition_worker',
        'srt_maker.ui.settings_dialog',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'tkinter',
        'unittest',
        'pytest',
        'setuptools',
        'pip',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='srt_maker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='srt_maker',
)
